spring.application.name=roommate-application
server.port=8080

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

weather.api.geocoding-url=https://geocoding-api.open-meteo.com/v1/search
weather.api.forecast-url=https://api.open-meteo.com/v1/forecast
weather.api.forecast-days=5
weather.api.timeout-ms=4000
